cerepairs/Controllers/SecurityController.cs
using System;
using System.Web;
using System.Web.Mvc;
using hme.Models;
using System.Web.Security;

using hmeUtil;
using HME.SQLSERVER.DAL;
using Microsoft.AspNet.Identity;
using System.Linq;
using cerepairs.Models;
using System.Configuration;
using System.Collections.Generic;
using System.Threading.Tasks;
using RazorEngine;
using qalab;
using cerepairs;
using System.Web.Script.Serialization;

namespace hme
{
    public class SecurityController : Controller
    {
        public static string salt = "Ek#JkkL-KSDFfort%93K,&MKmowmfom;spw,mfv";

        public object ExceptionUtility { get; private set; }

        [HttpPost]
        [AllowAnonymous]
        public JsonResult JSON_Login(login_dto dto)
        {
            bool isAdmin = false;
            bool isFullAdmin = false;
            string loginType = "ldap";
            string userUID = "";
            User user = null;
            ViewBag.loginerror = "";

            AccountViewModels accountViewModels = new AccountViewModels();
            UserLogin userlogin = accountViewModels.User_Login(dto.username, dto.password);
            if (userlogin != null)
            {
                user = new User() { Username = dto.username.Split('@')[0], Password = dto.password };
                loginType = "customerservice";
                user.Email = dto.username;
                user.CN = userlogin.CN;
                userUID = userlogin.User_UID;
                user.Givenname = userlogin.Givenname;
                user.SN = userlogin.SN;
                //user.Roles = "Users,Admin";
                if (userlogin.UserType_ID == "1")
                {
                    isAdmin = true;
                }
                if (userlogin.UserType_ID == "4")
                {
                    isAdmin = true;
                    isFullAdmin = true;
                }
                user.Roles = "User" + (isAdmin ? ",Admin" : "") + (isFullAdmin ? ",FullAdmin" : "");

            }
            if (user != null)
            {
                User_Info user_info = new User_Info();
                user_info.cn = user.CN;
                //user_info.company_master = Session["Company_Master"].ToString();
                user_info.email = user.Email;
                user_info.givenname = user.Givenname;
                user_info.sn = user.SN;
                user_info.isadmin = isAdmin.ToString().ToLower();
                user_info.isfulladmin = isFullAdmin.ToString().ToLower();
                user_info.logintype = loginType;
                user_info.useruid = userUID;
                user_info.SamAccountname = user.SamAccountname;
                return Json(user_info);

            }
            else
            {
                //ModelState.AddModelError("", "Invalid login attempt.");
                //ViewBag.loginerror = "Invalid login attempt.";
                return null;
            }
        }

        [AllowAnonymous]
        public ActionResult Login(string returnUrl)
        {
            if (RuntimeCaching.GetLoginAttempts(Request.ServerVariables["REMOTE_ADDR"].ToString() + "delay") != 0)
            {
                return View("LoginAttemptsExceeded");
            }
            ViewBag.ReturnUrl = returnUrl;
            ViewBag.loginerror = "";
            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public ActionResult Login(LoginViewModel model, string returnUrl)
        {
            if (RuntimeCaching.GetLoginAttempts(Request.ServerVariables["REMOTE_ADDR"].ToString() + "delay") != 0)
            {
                return View("LoginAttemptsExceeded");
            }
            RuntimeCaching.CacheLoginAttempts(Request.ServerVariables["REMOTE_ADDR"].ToString());
            bool isAdmin = false;
            bool isFullAdmin = false;
            string loginType = "ldap";
            string userUID = "";
            ldap ldap = new ldap();
            User user;
            ViewBag.loginerror = "";

            if (!ModelState.IsValid)
            {
                ViewBag.loginerror = "Invalid login attempt.";
                return View(model);
            }

            AccountViewModels accountViewModels = new AccountViewModels();
            UserLogin userlogin = accountViewModels.User_Login(model.Username, model.Password);
            if (userlogin != null)
            {
                user = new User() { Username = model.Username.Split('@')[0], Password = model.Password };
                loginType = "customerservice";
                user.Email = model.Username;
                user.CN = userlogin.CN;
                userUID = userlogin.User_UID;
                user.Givenname = userlogin.Givenname;
                user.SN = userlogin.SN;
                //user.Roles = "Users,Admin";
                if (userlogin.UserType_ID == "1")
                {
                    isAdmin = true;
                }
                if (userlogin.UserType_ID == "4")
                {
                    isAdmin = true;
                    isFullAdmin = true;
                }
                user.Roles = "User" + (isAdmin ? ",Admin" : "") + (isFullAdmin ? ",FullAdmin" : "");

            }
            else
            {
                user = new User() { Username = model.Username.Split('@')[0], Password = model.Password };
                user = ldap.GetUserDetails(user);
            }

            if (user != null)
            {
                RuntimeCaching.ClearCache(Request.ServerVariables["REMOTE_ADDR"].ToString());
                FormsAuthentication.SetAuthCookie(model.Username, false);
                if (loginType == "ldap")
                {
                    isAdmin = isFullAdmin = user.MemberOf.Where(x =>
                          x.Contains("# HMEAll") && Session["Company_Master"].ToString() == "hsc"
                       || x.Contains("# HSCAll") && Session["Company_Master"].ToString() == "hsc"
                       || x.Contains("# JTECH All") && Session["Company_Master"].ToString() == "jtch"
                       || x.Contains("# Commercial Electronics") && Session["Company_Master"].ToString() == "cel"
                       || x.Contains("# CC_Order_Portal_Admin") && Session["Company_Master"].ToString() == "clrc"
                       || x.Contains("# Executive Staff")
                       || x.Contains("# HME Officers")
                       || x.Contains("IT Department")
                    ).ToList().Count > 0 ? true : false;
                    user.Roles = "User" + (isAdmin ? ",Admin,FullAdmin" : "");
                }
                User_Info user_info = new User_Info();
                user_info.cn = user.CN;
                user_info.company_master = Session["Company_Master"].ToString();
                user_info.email = user.Email;
                user_info.givenname = user.Givenname;
                user_info.sn = user.SN;
                user_info.isadmin = isAdmin.ToString().ToLower();
                user_info.isfulladmin = isFullAdmin.ToString().ToLower();
                user_info.logintype = loginType;
                user_info.useruid = userUID;
                user_info.SamAccountname = user.SamAccountname;
                hmeUtil.Encryptor encryptor = new Encryptor();
                JavaScriptSerializer json = new JavaScriptSerializer();
                string token = encryptor.Encrypt(json.Serialize(user_info), salt);

                var authTicket = new FormsAuthenticationTicket(1, token, DateTime.Now, DateTime.Now.AddMinutes(30), false, user.Roles);
                //var authTicket = new FormsAuthenticationTicket(1, user.Email + "|" + userUID + "|" + user.CN + "|" + loginType + "|" + isAdmin.ToString().ToLower() + "|" + isFullAdmin.ToString().ToLower() + "|" + Session["Company_Master"].ToString() + "|" + user.Givenname + "|" + user.SN, DateTime.Now, DateTime.Now.AddMinutes(30), false, user.Roles);
                string encryptedTicket = FormsAuthentication.Encrypt(authTicket);
                var authCookie = new HttpCookie(FormsAuthentication.FormsCookieName, encryptedTicket);
                HttpContext.Response.Cookies.Add(authCookie);
                string decodedUrl = "";
                if (!string.IsNullOrEmpty(returnUrl))
                {
                    decodedUrl = Server.UrlDecode(returnUrl);
                }

                if (Url.IsLocalUrl(decodedUrl))
                {
                    return Redirect(decodedUrl);
                }
                else
                {
                    return RedirectToAction("Index", "Home");
                }
                //return RedirectToAction("Index", "Home");
            }
            else
            {
                ModelState.AddModelError("", "Invalid login attempt.");
                ViewBag.loginerror = "Invalid login attempt.";
                return View(model);
            }
        }


        //
        // POST: /Security/LogOff
        //[ValidateAntiForgeryToken]
        public ActionResult LogOff()
        {
            //AuthenticationManager.SignOut(DefaultAuthenticationTypes.ApplicationCookie);
            try
            {
                FormsAuthentication.SignOut();
            }
            catch { }
            return RedirectToAction("Index", "Home");
        }


        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> ResetPassword(ResetPasswordViewModel model)
        {

            if (RuntimeCaching.CacheIsForgotPassword(model.Code))
            {
                AccountViewModels accountViewModels = new AccountViewModels();
                string user_uid = accountViewModels.Update_Pass_Reset(model.Code);
                string salt = string.Empty;
                string User_PasswordHash;
                if (user_uid != null)
                {
                    UserSearchRequest searchdto = new UserSearchRequest();

cerepairs/Views/Security/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

cerepairs/Views/Security/ForgotPassword.cshtml
@model hme.Models.ForgotPasswordViewModel
@{
    ViewBag.Title = "Forgot your password?";
    Layout = "~/Views/Shared/_LayoutLogin.cshtml";
}


<h2>@ViewBag.Title</h2>

@using (Html.BeginForm("ForgotPassword", "Security", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()
    <h4>Enter your email.</h4>
    <hr />
    @Html.ValidationSummary("", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(m => m.Email, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Email, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" class="btn btn-default" value="Submit" />
        </div>
    </div>
}

cerepairs/Views/Security/Login.cshtml
@using hme.Models
@model LoginViewModel
@{
    ViewBag.Title = "Log in";
    Layout = "~/Views/Shared/_LayoutLogin.cshtml";
}

<div class="container container-table">
    <div id="Content" class="content-login">
        @using (Html.BeginForm("Login", "Security", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
            {
            @Html.AntiForgeryToken()
            <div class="col-lg-9 col-centered no-pad animated fadeIn">
                <div class="form-message form-notice" style="margin-bottom:70px;">
                    <p>Please note: Our password policy has changed and as such you may need to reset your password to gain access to the Customer Service Portal. To do this, please click the "Forgot your password?" link and we'll email you instructions to help you reset your password.</p>
                </div>
            </div>
            <div class="col-lg-9 col-centered container-login animated fadeIn ">
                <div class="col-lg-6 col-login-left">
                    <div class="form-group">
                        <div class="brand-login-sm hidden-lg col-md-12">

                            <img src="/images/ce.png" alt="CE Repairs" class="center-block" />

                        </div>
                        <div class="col-lg-12 text-center">
                            <h4>New Customers</h4>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-lg-4 col-md-4 col-sm-4"></div>
                        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
                            <a href="/security/Register" class="btn btn-default form-control">Register</a>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-lg-12 register-phone text-center">
                            <p>
                                <strong>
                                    Register by phone at


                                    1-800-279-3939


                                </strong>
                            </p>
                        </div>
                    </div>
                    <div class="form-group visible-lg" style="margin-bottom:0px;">
                        <div class="col-lg-12 security-warning">
                            <p><strong>Security Warning:</strong><br />It is your responsibility to maintain the confidentiality and control of passwords used to access data through our website. For your protection, we strongly recommend that you do not provide your account information, user name, or password to anyone. If you become aware of any suspicious activity relating to your account, please contact us immediately.</p>
                            <p>To protect access to your information we recommend using at least eight characters, two of which should be special characters or numbers. Change your password frequently and especially after employees leave your company. Do not leave your computer unattended while logged in and log out when finished.</p>
                        </div>
                    </div>
                </div>
                <div class="col-lg-6 col-login-right">
                    <div class="form-group visible-lg">
                        <div class="col-lg-12">
                            <div class="brand-login">
                                <img src="/images/ce.png" alt="CE Repairs" />
                            </div>
                        </div>
                        <div class="col-lg-12 text-center">
                            <div class="brand-login-header">Customer Service Portal</div>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-lg-2"></div>
                        <div class="col-lg-8">
                            <input type="text" maxlength="100" name="Username" class="form-control" value="" placeholder="Email" />
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-lg-2"></div>
                        <div class="col-lg-8">
                            <input type="password" maxlength="16" name="Password" class="form-control" value="" placeholder="Password" />
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-lg-3"></div>
                        <div class="col-lg-6">
                            <input type="submit" value="Login" class="btn btn-primary form-control btn-submit" />
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-lg-12 text-center">
                            <a href="/security/ForgotPassword">Forgot your password?</a>
                        </div>
                    </div>
                    @if (ViewBag.loginerror != "")
                    {
                    <div class="form-group">
                        <div class="col-lg-12 text-center" style="color:red;">
                            Invalid login attempt.
                        </div>
                    </div>
                    }
                </div>
            </div>
        }
    </div>
</div>

cerepairs/Views/Security/LoginAttemptsExceeded.cshtml
@{
    ViewBag.Title = "Log in";
    Layout = "~/Views/Shared/_LayoutLogin.cshtml";
}
<div class="col-lg-9 col-centered col-login-exceed text-center">
    <h4>Login attempts exceeded please try your request at a later time. Thank you.</h4>
</div>

cerepairs/Views/Security/PasswordResetConfirmed.cshtml
@{
    ViewBag.Title = "Reset Password";
    Layout = "~/Views/Shared/_LayoutLogin.cshtml";
}

<div class="container container-main">
    <div id="Content">
        <div class="col-lg-12">
            <h2>Reset Password</h2>
        </div>
        <p>Password Reset Confirmed</p>
        <p>Please <a href="@ViewBag.URL/security/login/">login</a> to your account.</p>
    </div>
</div>

cerepairs/Views/Security/RegisterResponse.cshtml
@{
    ViewBag.Title = "Register";
    Layout = "~/Views/Shared/_LayoutLogin.cshtml";
}

<div class="container container-main">
    <div id="Content">
        <div class="col-lg-12">
            <h2>Registration</h2>
        </div>
        <div class="col-lg-12">
            <div class="form-message form-success">
                <ul>
                    <li>Registration Complete! You will be notified within 1-2 business days regarding your account access. Thank you.</li>
                </ul>
            </div>
        </div>
    </div>
</div>

cerepairs/Views/Security/ResetPassword.cshtml
@using hme.Models
@model ResetPasswordViewModel
@{
    ViewBag.Title = "Log in";
    Layout = "~/Views/Shared/_LayoutLogin.cshtml";
}
<style>
    .red {
        color: red;
    }

    .pop-msg2 {
        position: absolute;
        color: red;
        font-size: 20px;
        text-align: left;
        z-index: 99999;
        background-color: #fff;
        border: solid 1px #337ab7;
        padding: 5px 5px 5px 5px;
    }
</style>
<div class="container container-main">
    <div id="Content">
    <div class="col-lg-12">
        <h2 class="resetpassword-header">Reset Password</h2>
    </div>
    @using (Html.BeginForm("ResetPassword", "Security", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-horizontal col-lg-12", role = "form" }))
            {
        @Html.AntiForgeryToken()

            <div class="col-lg-6">
                <div class="form-group">
                    <label for="Password" class="control-label col-lg-5">New Password:</label>
                    <div class="col-lg-7">
                        <input type="password" maxlength="16" id="Password" name="Password" class="form-control" value="">
                    </div>
                </div>
                <div class="form-group">
                    <label for="ConfirmPassword" class="control-label col-lg-5">Confirm Password:</label>
                    <div class="col-lg-7">
                        <input type="password" maxlength="16" id="ConfirmPassword" name="ConfirmPassword" class="form-control" value="">
                        <input type="hidden" maxlength="16" name="code" value="@Model.Code">

                    </div>
                </div>
                <div class="form-group">
                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 pull-right">
                        <div class="pass-req-cont">
                            <p><strong><i style="border:none;" class="fa fa-lock" aria-hidden="true"></i> Password Requirements</strong></p>
                            <ul>
                                <li>The length of the password must be at least eight (8) characters and not more than sixteen (16) characters.</li>
                                <li>The password may not contain blank spaces.</li>
                                <li>
                                    The password must contain at least one (1) character from each of the three (3) groups below:
                                    <ul>
                                        <li>English uppercase characters (A through Z)</li>
                                        <li>English lowercase characters (a through z)</li>
                                        <li>Numerals (0 through 9)</li>
                                    </ul>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-lg-3"></div>
                    <div class="col-lg-7" style="text-align:center;">
                        <input type="submit" value="Reset Password" id="resetpassword" name="resetpassword" class="btn btn-primary form-control">
                    </div>
                </div>
            </div>

    }
            <div class="col-lg-7">
                <p class="respass-note">*If you are a CEREPAIRS employee, please contact the IT department for assistance.</p>
            </div>
        </div>
 
</div>

cerepairs/Views/Security/ResetPasswordEmailInvalid.cshtml
@{
    ViewBag.Title = "Reset Password";
    Layout = "~/Views/Shared/_LayoutLogin.cshtml";
}

<div class="container container-main">
    <div id="Content">
        <div class="col-lg-12">
            <h2>Reset Password</h2>
        </div>
        <p>Invalid Email Address.</p>
        <p>Please click <a href="@ViewBag.Forogot_URL">here</a> to re-enter your email address.</p>
    </div>
</div>

cerepairs/Views/Security/ResetPasswordExpired.cshtml
@{
    ViewBag.Title = "Reset Password";
    Layout = "~/Views/Shared/_LayoutLogin.cshtml";
}

<div class="container container-main">
    <div id="Content">
        <div class="col-lg-12">
            <h2>Reset Password</h2>
        </div>
        <p>Password Reset Request has expired.</p>
    </div>
</div>

cerepairs/Views/Security/ResetPasswordResponse.cshtml
@{
    ViewBag.Title = "Reset Password";
    Layout = "~/Views/Shared/_LayoutLogin.cshtml";
}

<div class="container container-main">
    <div id="Content">
        <div class="col-lg-12">
            <h2>Reset Password</h2>
        </div>
        <p>Password Reset Request has been sent to <strong>@ViewBag.Email</strong>.</p>
        <p>Please check your email to reset your password.</p>
    </div>
</div>